---
version: "2.1"
services:
    radarr:
        image: lscr.io/linuxserver/radarr:5.0.2-nightly
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./data:/config
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 7878:7878
