---
version: "2.1"
services:
    nzbhydra2:
        image: lscr.io/linuxserver/nzbhydra2:latest
        container_name: nzbhydra2
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./data/hydra:/config
        ports:
            - 5077:5076
        restart: unless-stopped
    mynzbhydra2:
        image: hydradocker:latest
        container_name: mynzbhydra2
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./data/myhydra:/data
        ports:
            - 5078:5076
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./data/jackett:/config
        ports:
            - 9117:9117
        restart: unless-stopped
